
import SwiftUI

struct TermsView: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        NavigationView {
            ZStack {
                // Dark Theme Background
                Color(red: 0.11, green: 0.11, blue: 0.11)
                    .ignoresSafeArea()
                
                ScrollView {
                    VStack(alignment: .leading, spacing: 20) {
                        // Header
                        VStack(spacing: 8) {
                            Image("LUNRICON") // Assuming this asset exists based on Launch Screen requirement
                                .resizable()
                                .scaledToFit()
                                .frame(width: 80, height: 80)
                                .clipShape(RoundedRectangle(cornerRadius: 16))
                                .shadow(radius: 10)
                            
                            Text("Eclipse")
                                .font(.largeTitle.bold())
                                .foregroundStyle(.white)
                            
                            Text("2025")
                                .font(.title3)
                                .foregroundStyle(.white.opacity(0.7))
                            
                            Text("Creator: Jaxon Smith")
                                .font(.headline)
                                .foregroundStyle(.blue)
                                .padding(.top, 4)
                        }
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 30)
                        
                        // Terms Text
                        Group {
                            Text("Terms of Use")
                                .font(.title2.bold())
                                .foregroundStyle(.white)
                            
                            Text("""
                                Welcome to Eclipse. By using this application, you agree to the following terms and conditions.
                                
                                1. Usage Policy
                                Eclipse is an AI-powered assistant designed to help with daily tasks, creativity, and information. You agree to use this service responsibly and not for any illegal or harmful activities.
                                
                                2. Privacy
                                We respect your privacy. Chats are stored securely on Firebase. Ensure you do not share sensitive personal information (PII) like credit card numbers or passwords in your conversations.
                                
                                3. Content Generation
                                AI responses are generated by Google's Gemini models. While we strive for accuracy, AI can make mistakes. Please verify important information.
                                
                                4. User Content
                                You retain ownership of the content you provide. By using Eclipse, you grant us the right to process your inputs to generate responses.
                                
                                5. Termination
                                We reserve the right to terminate or suspend access to our service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                                
                                6. Disclaimer
                                The service is provided on an "AS IS" and "AS AVAILABLE" basis.
                                
                                7. Contact
                                For support or inquiries, please contact Jaxon Smith.
                                """)
                                .font(.body)
                                .foregroundStyle(.white.opacity(0.8))
                                .lineSpacing(4)
                        }
                        .padding(.horizontal)
                        
                        Spacer(minLength: 50)
                    }
                }
            }
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") {
                        dismiss()
                    }
                    .font(.headline)
                }
            }
        }
    }
}
